# -*- mode: python -*-

block_cipher = None


a = Analysis(['sd_watcher_afk/__main__.py'],
             pathex=[],
             binaries=None,
             datas=None,
             hiddenimports=[
                'Xlib.keysymdef.miscellany',
                'Xlib.keysymdef.latin1',
                'Xlib.keysymdef.latin2',
                'Xlib.keysymdef.latin3',
                'Xlib.keysymdef.latin4',
                'Xlib.keysymdef.greek',
                'Xlib.support.unix_connect',
                'Xlib.ext.shape',
                'Xlib.ext.xinerama',
                'Xlib.ext.composite',
                'Xlib.ext.randr',
                'Xlib.ext.xfixes',
                'Xlib.ext.security',
                'Xlib.ext.xinput',
                'pynput.keyboard._xorg',
                'pynput.mouse._xorg',
                'pynput.keyboard._win32',
                'pynput.mouse._win32',
                'pynput.keyboard._darwin',
                'pynput.mouse._darwin',
             ],
             hookspath=[],
             runtime_hooks=[],
              excludes=[
               'PySide6.QtWebChannel', 
               'PySide6.QtWebEngineCore', 
               'PySide6.QtWebEngineWidgets',
               'PySide6.QtWebContext',
               'PySide6.QtNetwork',
               'PySide6.QtCore',
               'PySide6.QtGui',
               'PySide6.QtSvg',
               'PySide6.QtWidgets',
               'PySide6.QtSvg',
               'PySide6.QtQuick',
               'PySide6.QtQml',
            ],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          exclude_binaries=True,
          name='sd-watcher-afk',
          contents_directory=".",
          debug=False,
          strip=False,
          upx=True,
          console=True )
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=True,
               name='sd-watcher-afk')
